apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
      - name: conversao
        image: jotalima72/conv-temp:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conv-temp
spec:
  selector:
    app: conv-temp
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
